// Package bus implements the CQRS command bus.
//
// A Command is an intent to change state. Commands are dispatched through the
// CommandBus, which routes them to the registered CommandHandler.
//
// Key design decisions:
//   - Commands return only error (never a result value). If the caller needs
//     the ID of a newly created resource, the ID is pre-generated by the caller
//     and passed inside the command struct.
//   - One handler per command type — enforced by reflect.Type lookup.
//   - The InMemoryCommandBus uses reflect.Type as the map key, which is the
//     idiomatic Go approach for a generic bus without generics ceremony.
package bus

import (
	"context"
	"fmt"
	"reflect"
)

// Command is the marker interface for all commands.
// Every concrete command struct (CreateTodoCommand, etc.) satisfies this.
type Command interface{}

// CommandHandler processes a single command type.
// Each command has exactly one handler registered in the bus.
type CommandHandler interface {
	Handle(ctx context.Context, cmd Command) error
}

// CommandBus dispatches commands to their registered handlers.
// This is the application-layer seam: the HTTP adapter calls Dispatch without
// knowing which handler will process the command.
type CommandBus interface {
	Dispatch(ctx context.Context, cmd Command) error
}

// InMemoryCommandBus is the default CommandBus implementation.
// It routes commands to handlers using a reflect.Type → handler map.
// This is suitable for a monolith; replace with a message-broker-backed
// implementation to distribute commands across services.
type InMemoryCommandBus struct {
	handlers map[reflect.Type]CommandHandler
}

func NewInMemoryCommandBus() *InMemoryCommandBus {
	return &InMemoryCommandBus{
		handlers: make(map[reflect.Type]CommandHandler),
	}
}

// Register associates a command type with a handler.
// Call this during application wiring (main.go) for each command.
// The cmd argument is used only for its type — pass a zero-value struct.
func (b *InMemoryCommandBus) Register(cmd Command, handler CommandHandler) {
	b.handlers[reflect.TypeOf(cmd)] = handler
}

// Dispatch finds the handler for cmd and calls Handle.
// Returns an error if no handler is registered for the command type.
func (b *InMemoryCommandBus) Dispatch(ctx context.Context, cmd Command) error {
	handler, ok := b.handlers[reflect.TypeOf(cmd)]
	if !ok {
		return fmt.Errorf("no handler registered for command %T", cmd)
	}

	return handler.Handle(ctx, cmd)
}
