// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: components.sql

package commanddb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (
    id,
    name,
    description,
    code,
    manufacturer,
    manufacturer_url,
    price,
    weight_g,
    quantity,
    image_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, description, code, manufacturer, manufacturer_url, price, weight_g, quantity, image_url, created_at
`

type CreateComponentParams struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	Code            string         `json:"code"`
	Manufacturer    pgtype.Text    `json:"manufacturer"`
	ManufacturerUrl pgtype.Text    `json:"manufacturer_url"`
	Price           pgtype.Numeric `json:"price"`
	WeightG         pgtype.Int4    `json:"weight_g"`
	Quantity        int32          `json:"quantity"`
	ImageUrl        pgtype.Text    `json:"image_url"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Code,
		arg.Manufacturer,
		arg.ManufacturerUrl,
		arg.Price,
		arg.WeightG,
		arg.Quantity,
		arg.ImageUrl,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Manufacturer,
		&i.ManufacturerUrl,
		&i.Price,
		&i.WeightG,
		&i.Quantity,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components WHERE id = $1
`

func (q *Queries) DeleteComponent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComponent, id)
	return err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, name, description, code, manufacturer, manufacturer_url, price, weight_g, quantity, image_url, created_at FROM components WHERE id = $1
`

func (q *Queries) GetComponentByID(ctx context.Context, id uuid.UUID) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByID, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Manufacturer,
		&i.ManufacturerUrl,
		&i.Price,
		&i.WeightG,
		&i.Quantity,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateComponent = `-- name: UpdateComponent :exec
UPDATE components SET
    name             = $2,
    description      = $3,
    manufacturer     = $4,
    manufacturer_url = $5,
    price            = $6,
    weight_g         = $7,
    quantity         = $8,
    image_url        = $9
WHERE id = $1
`

type UpdateComponentParams struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	Manufacturer    pgtype.Text    `json:"manufacturer"`
	ManufacturerUrl pgtype.Text    `json:"manufacturer_url"`
	Price           pgtype.Numeric `json:"price"`
	WeightG         pgtype.Int4    `json:"weight_g"`
	Quantity        int32          `json:"quantity"`
	ImageUrl        pgtype.Text    `json:"image_url"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) error {
	_, err := q.db.Exec(ctx, updateComponent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Manufacturer,
		arg.ManufacturerUrl,
		arg.Price,
		arg.WeightG,
		arg.Quantity,
		arg.ImageUrl,
	)
	return err
}
