// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package commanddb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID          int64            `json:"id"`
	EventName   string           `json:"event_name"`
	Payload     []byte           `json:"payload"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
}

type Todo struct {
	ID        uuid.UUID        `json:"id"`
	Title     string           `json:"title"`
	Completed bool             `json:"completed"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
