// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: outbox.sql

package commanddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (event_name, payload)
VALUES ($1, $2)
`

type InsertOutboxEventParams struct {
	EventName string `json:"event_name"`
	Payload   []byte `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.EventName, arg.Payload)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const selectUnpublishedOutboxEvents = `-- name: SelectUnpublishedOutboxEvents :many
SELECT id, event_name, payload, created_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY id
LIMIT 100
`

type SelectUnpublishedOutboxEventsRow struct {
	ID        int64            `json:"id"`
	EventName string           `json:"event_name"`
	Payload   []byte           `json:"payload"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) SelectUnpublishedOutboxEvents(ctx context.Context) ([]SelectUnpublishedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, selectUnpublishedOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectUnpublishedOutboxEventsRow{}
	for rows.Next() {
		var i SelectUnpublishedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventName,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
