// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package commanddb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id,
    name,
    description,
    price,
    tags
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, description, price, tags, created_at
`

type CreateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Tags        []string       `json:"tags"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Tags,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteProductComponent = `-- name: DeleteProductComponent :exec
DELETE FROM product_components
WHERE product_id = $1 AND component_id = $2
`

type DeleteProductComponentParams struct {
	ProductID   uuid.UUID `json:"product_id"`
	ComponentID uuid.UUID `json:"component_id"`
}

func (q *Queries) DeleteProductComponent(ctx context.Context, arg DeleteProductComponentParams) error {
	_, err := q.db.Exec(ctx, deleteProductComponent, arg.ProductID, arg.ComponentID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, tags, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const listProductComponentsByProductID = `-- name: ListProductComponentsByProductID :many
SELECT product_id, component_id, quantity
FROM product_components
WHERE product_id = $1
`

func (q *Queries) ListProductComponentsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductComponent, error) {
	rows, err := q.db.Query(ctx, listProductComponentsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductComponent{}
	for rows.Next() {
		var i ProductComponent
		if err := rows.Scan(&i.ProductID, &i.ComponentID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products SET
    name        = $2,
    description = $3,
    price       = $4,
    tags        = $5
WHERE id = $1
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Tags        []string       `json:"tags"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Tags,
	)
	return err
}

const upsertProductComponent = `-- name: UpsertProductComponent :exec
INSERT INTO product_components (product_id, component_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (product_id, component_id) DO UPDATE SET quantity = EXCLUDED.quantity
`

type UpsertProductComponentParams struct {
	ProductID   uuid.UUID `json:"product_id"`
	ComponentID uuid.UUID `json:"component_id"`
	Quantity    int32     `json:"quantity"`
}

func (q *Queries) UpsertProductComponent(ctx context.Context, arg UpsertProductComponentParams) error {
	_, err := q.db.Exec(ctx, upsertProductComponent, arg.ProductID, arg.ComponentID, arg.Quantity)
	return err
}
