// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package commanddb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteTodo(ctx context.Context, id uuid.UUID) error
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, id uuid.UUID) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	MarkOutboxEventPublished(ctx context.Context, id int64) error
	SelectUnpublishedOutboxEvents(ctx context.Context) ([]SelectUnpublishedOutboxEventsRow, error)
}

var _ Querier = (*Queries)(nil)
