package commands

import (
	"context"
	"fmt"
	"time"

	"github.com/C5383717/my-todo/internal/app/bus"
	"github.com/C5383717/my-todo/internal/domain"
	"github.com/google/uuid"
)

// CreateTodoCommand carries everything needed to create a new Todo.
//
// The ID is pre-generated by the HTTP handler (using uuid.New()) before
// dispatching this command. This is a deliberate CQRS design decision:
// commands do not return values, so the caller generates the ID and can
// include it in the 201 response immediately — no read-back query needed.
type CreateTodoCommand struct {
	ID          uuid.UUID
	Title       string
	Description *string
}

// CreateTodoHandler handles CreateTodoCommand.
// It depends only on domain PORTS (interfaces), never on concrete types.
// This means the handler can be tested with a mock repository.
type CreateTodoHandler struct {
	repo      domain.TodoRepository  // PORT — infrastructure implements this
	publisher domain.EventPublisher  // PORT — infrastructure implements this
}

func NewCreateTodoHandler(repo domain.TodoRepository, publisher domain.EventPublisher) *CreateTodoHandler {
	return &CreateTodoHandler{repo: repo, publisher: publisher}
}

// Handle implements bus.CommandHandler.
// Flow:
//  1. Type-assert the generic Command to CreateTodoCommand
//  2. Call domain.NewTodo — constructor validates and builds the aggregate
//  3. Persist via the repository port
//  4. Publish TodoCreated domain event
func (h *CreateTodoHandler) Handle(ctx context.Context, cmd bus.Command) error {
	c, ok := cmd.(CreateTodoCommand)
	if !ok {
		return fmt.Errorf("CreateTodoHandler: unexpected command type %T", cmd)
	}

	todo, err := domain.NewTodo(c.ID, c.Title, c.Description)
	if err != nil {
		// domain.ErrTitleRequired — apierrors will map this to 400
		return fmt.Errorf("create todo: %w", err)
	}

	if err := h.repo.Create(ctx, todo); err != nil {
		return fmt.Errorf("create todo: persist: %w", err)
	}

	if err := h.publisher.Publish(ctx, domain.TodoCreated{
		TodoID:     todo.ID,
		Title:      todo.Title,
		OccurredAt: time.Now().UTC(),
	}); err != nil {
		// Event publishing failure is non-fatal in this implementation.
		// In production you might want to log and continue, or use an outbox pattern.
		return fmt.Errorf("create todo: publish event: %w", err)
	}

	return nil
}
