//go:build go1.22

// Package todoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package todoapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TodoResponseStatus.
const (
	TodoResponseStatusDone    TodoResponseStatus = "done"
	TodoResponseStatusPending TodoResponseStatus = "pending"
)

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// DetailedError defines model for DetailedError.
type DetailedError struct {
	Code string `json:"code"`

	// Context Additional context of the error
	Context *map[string]interface{} `json:"context,omitempty"`
	Message string                  `json:"message"`

	// RequestID The unique identifier of the request
	RequestID *string `json:"requestID,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`
}

// Error A structured error response
type Error struct {
	Code string `json:"code"`

	// Context Additional context
	Context *map[string]interface{} `json:"context,omitempty"`
	Message string                  `json:"message"`
}

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	Error DetailedError `json:"error"`
}

// TodoListResponse defines model for TodoListResponse.
type TodoListResponse struct {
	Items []TodoResponse `json:"items"`
}

// TodoResponse defines model for TodoResponse.
type TodoResponse struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Status      TodoResponseStatus `json:"status"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// TodoResponseStatus defines model for TodoResponse.Status.
type TodoResponseStatus string

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// N400 defines model for 400.
type N400 = ErrorMessage

// N404 defines model for 404.
type N404 = ErrorMessage

// N409 defines model for 409.
type N409 = ErrorMessage

// N500 defines model for 500.
type N500 = ErrorMessage

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all TODO items
	// (GET /todos)
	ListTodos(w http.ResponseWriter, r *http.Request)
	// Create a new TODO item
	// (POST /todos)
	CreateTodo(w http.ResponseWriter, r *http.Request)
	// Permanently delete a TODO item
	// (DELETE /todos/{id})
	DeleteTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a single TODO item by ID
	// (GET /todos/{id})
	GetTodoById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update title and description of a TODO item
	// (PUT /todos/{id})
	UpdateTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Mark a TODO item as done
	// (POST /todos/{id}/complete)
	CompleteTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTodos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTodo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTodoById operation middleware
func (siw *ServerInterfaceWrapper) GetTodoById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTodoById(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteTodo operation middleware
func (siw *ServerInterfaceWrapper) CompleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/todos", wrapper.ListTodos)
	m.HandleFunc("POST "+options.BaseURL+"/todos", wrapper.CreateTodo)
	m.HandleFunc("DELETE "+options.BaseURL+"/todos/{id}", wrapper.DeleteTodo)
	m.HandleFunc("GET "+options.BaseURL+"/todos/{id}", wrapper.GetTodoById)
	m.HandleFunc("PUT "+options.BaseURL+"/todos/{id}", wrapper.UpdateTodo)
	m.HandleFunc("POST "+options.BaseURL+"/todos/{id}/complete", wrapper.CompleteTodo)

	return m
}

type N400JSONResponse ErrorMessage

type N404JSONResponse ErrorMessage

type N409JSONResponse ErrorMessage

type N500JSONResponse ErrorMessage

type ListTodosRequestObject struct {
}

type ListTodosResponseObject interface {
	VisitListTodosResponse(w http.ResponseWriter) error
}

type ListTodos200JSONResponse TodoListResponse

func (response ListTodos200JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTodos500JSONResponse struct{ N500JSONResponse }

func (response ListTodos500JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTodoRequestObject struct {
	Body *CreateTodoJSONRequestBody
}

type CreateTodoResponseObject interface {
	VisitCreateTodoResponse(w http.ResponseWriter) error
}

type CreateTodo201JSONResponse TodoResponse

func (response CreateTodo201JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTodo400JSONResponse struct{ N400JSONResponse }

func (response CreateTodo400JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTodo500JSONResponse struct{ N500JSONResponse }

func (response CreateTodo500JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTodoRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteTodoResponseObject interface {
	VisitDeleteTodoResponse(w http.ResponseWriter) error
}

type DeleteTodo204Response struct {
}

func (response DeleteTodo204Response) VisitDeleteTodoResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTodo404JSONResponse struct{ N404JSONResponse }

func (response DeleteTodo404JSONResponse) VisitDeleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTodo500JSONResponse struct{ N500JSONResponse }

func (response DeleteTodo500JSONResponse) VisitDeleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTodoByIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetTodoByIdResponseObject interface {
	VisitGetTodoByIdResponse(w http.ResponseWriter) error
}

type GetTodoById200JSONResponse TodoResponse

func (response GetTodoById200JSONResponse) VisitGetTodoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTodoById404JSONResponse struct{ N404JSONResponse }

func (response GetTodoById404JSONResponse) VisitGetTodoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTodoById500JSONResponse struct{ N500JSONResponse }

func (response GetTodoById500JSONResponse) VisitGetTodoByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTodoRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateTodoJSONRequestBody
}

type UpdateTodoResponseObject interface {
	VisitUpdateTodoResponse(w http.ResponseWriter) error
}

type UpdateTodo200JSONResponse TodoResponse

func (response UpdateTodo200JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTodo400JSONResponse struct{ N400JSONResponse }

func (response UpdateTodo400JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTodo404JSONResponse struct{ N404JSONResponse }

func (response UpdateTodo404JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTodo500JSONResponse struct{ N500JSONResponse }

func (response UpdateTodo500JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTodoRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type CompleteTodoResponseObject interface {
	VisitCompleteTodoResponse(w http.ResponseWriter) error
}

type CompleteTodo200JSONResponse TodoResponse

func (response CompleteTodo200JSONResponse) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTodo404JSONResponse struct{ N404JSONResponse }

func (response CompleteTodo404JSONResponse) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTodo409JSONResponse struct{ N409JSONResponse }

func (response CompleteTodo409JSONResponse) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTodo500JSONResponse struct{ N500JSONResponse }

func (response CompleteTodo500JSONResponse) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all TODO items
	// (GET /todos)
	ListTodos(ctx context.Context, request ListTodosRequestObject) (ListTodosResponseObject, error)
	// Create a new TODO item
	// (POST /todos)
	CreateTodo(ctx context.Context, request CreateTodoRequestObject) (CreateTodoResponseObject, error)
	// Permanently delete a TODO item
	// (DELETE /todos/{id})
	DeleteTodo(ctx context.Context, request DeleteTodoRequestObject) (DeleteTodoResponseObject, error)
	// Get a single TODO item by ID
	// (GET /todos/{id})
	GetTodoById(ctx context.Context, request GetTodoByIdRequestObject) (GetTodoByIdResponseObject, error)
	// Update title and description of a TODO item
	// (PUT /todos/{id})
	UpdateTodo(ctx context.Context, request UpdateTodoRequestObject) (UpdateTodoResponseObject, error)
	// Mark a TODO item as done
	// (POST /todos/{id}/complete)
	CompleteTodo(ctx context.Context, request CompleteTodoRequestObject) (CompleteTodoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListTodos operation middleware
func (sh *strictHandler) ListTodos(w http.ResponseWriter, r *http.Request) {
	var request ListTodosRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTodos(ctx, request.(ListTodosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTodos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTodosResponseObject); ok {
		if err := validResponse.VisitListTodosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTodo operation middleware
func (sh *strictHandler) CreateTodo(w http.ResponseWriter, r *http.Request) {
	var request CreateTodoRequestObject

	var body CreateTodoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTodo(ctx, request.(CreateTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTodoResponseObject); ok {
		if err := validResponse.VisitCreateTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTodo operation middleware
func (sh *strictHandler) DeleteTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteTodoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTodo(ctx, request.(DeleteTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTodoResponseObject); ok {
		if err := validResponse.VisitDeleteTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTodoById operation middleware
func (sh *strictHandler) GetTodoById(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetTodoByIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTodoById(ctx, request.(GetTodoByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTodoById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTodoByIdResponseObject); ok {
		if err := validResponse.VisitGetTodoByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTodo operation middleware
func (sh *strictHandler) UpdateTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateTodoRequestObject

	request.Id = id

	var body UpdateTodoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTodo(ctx, request.(UpdateTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTodoResponseObject); ok {
		if err := validResponse.VisitUpdateTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteTodo operation middleware
func (sh *strictHandler) CompleteTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request CompleteTodoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteTodo(ctx, request.(CompleteTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteTodoResponseObject); ok {
		if err := validResponse.VisitCompleteTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RY727bOBJ/lQHvPrRYxVa6Tq/1fnJj765xSZy67gKLvSJgxLHNrUSqJJXECAzcp3uA",
	"wz3hPslhSFmyLDdNukmBzYdYtsj5++OPM3PLEp3lWqFylvVvmUGba2XRf+nFMX0kWjlUjh55nqcy4U5q",
	"1f3dakW/4Q3P8hQb2+n5iqeFf0BjtAmCBLI++2VwMh4OZuPJ2cVoOp1MWcQytJYv6OUUPxVoHVxqsQKl",
	"HZB9qeTKwbV0S7A5JnJe2sAiZh13hWX9Xhyv1+t1xGyyxIyTur8bnLM++1u3drEb3truiGw6LbX6fQJt",
	"YmTuxfbZGy7ABFPYOmK9uPcUkZhNhpOLs8ns4sfJ+7NhIw4zLbT3f64LJRqO9h7T0TPt4Eevwrv5+snc",
	"HJxMR4PhrxfHk9Pzk9FstOPuUlpw5LO0wFODXKxC6tFh0/3Xj+n+sVbzVCY+yUdPA/fx2Ww0PRucXLwb",
	"TX8ZTfdgfqwcGsVTsGiu0ECQUPt89LjYrtS9C+r8elbL964dG+QOCYXliaQfc6NzNE4G7xtSq8CwPjuV",
	"6ccIcLGwEVxSKslbfnOCauGWrP8ijuOIuVVOa60zUi0o/E66FJuC3hQrWBidoCGVTSFHRxHLpNp8P2xJ",
	"XEeMTrA0KFj/t1L8h2qZvvwdQ96H6LhMUYw2ieNpOpmz/m/3CDNbR7th8fi5ca0IsYEQkh55CuUa0HNw",
	"S6wS3jKtpKDxsC1ttkQolPxUIEiBysm5RLMRuKGuaCuYh+XfwZ5/mz+2Jy8bFO4a8PNsdg7hJXioV3ul",
	"crhA00pBKamdg31ZqbKxE0SwzhSJKwyKEDeoTmHUyoTYAVSLcFvePiB7+xJWHeqG1jojKALLXXPbYPe7",
	"sVuGdyP8s+E6rbU3I1Fx0l2Abp6DXRuCiH2qiSROpHXTLTZsqpcOs+bDXXYE0illrSuF3Bi+apkVJH7O",
	"rM+blHh+EwOf6bk2GXeszwR3eOBkhvug8SC+a+2Wornp6CjGV704PsAXry8Peoeid8D/cfjyoNd7+fLo",
	"qNeL4zhmUW1aUUhx9/FEVWQUkhyVoJcRE1p5tNRa63dfw7+tPUUuHhbF3ex5l7ziypNoKzfbGvbl+L1/",
	"+0i3VARG29Y983WXFXAlYJ7qazRPdXHROqnmeh9HEs/BVvUCAjOtrDPcSbWA4XAI38HPeMMXntAGJllK",
	"h55V4Ts4fjt914FjnWVcCQtZ4bhDT/X4A3wqgoMUsfBbB0Y8WQIFPSjLeE7FHOANT1y6Aq2QajmSBtp4",
	"CSsQ0ubcJUtixKXRxWLpb65toy8L2/mXqhAS6BsG52MWsSs0Nnh72Ik7MeVE56h4Llmffd+JO9/TdcDd",
	"0oOgS6Trnxa4h9vfvh9Nf4U//v2/2ioLRGmELPuW7O3AFF1hFFWnqedwC9oIpGvocgUesmQzwR6eKbym",
	"JmYujXXPaSsXB1qlqx9AIZVcThdexyYqVgoMrlZRHAvWZ5UNLGq2Zi/uVaver15s8feemnHyz60KeZ+w",
	"yrouLfLFZJFl3KxKL3zYfP4CY68jlmu7JxfHk9PTwdlwNxt1PVrisgN0rY6H1DDkBg8WqChyIR2EJF+f",
	"LLkSKRp/HKVK0kIgPfgFL+LDqnbwzaUuHHAP7INLnnwMQN2XltoYVtVob7RYPVpK2tX3ukkLzhS4bmHi",
	"8FExcRcegoFl03gPUNCirwdQ0AYcFF7XIPKLwsnu3kqxDliihvHeqBr65Q1UbY55L+7B9RIDVEgdCI2h",
	"aMMbad0+XNTi2ue11zbqTMNxmax6xvClOPb+RBzP0WSclqUrCJECvh3P6AH0+BN6ZnqzGg93CHJkDL05",
	"084PFuBZL+49D7FUGjLaT5eQwUQbEYJp90Wz1iCemv6+TH3fIDs/IdGPlWqRYp0VorPx0PMlNzxDRxUF",
	"9aaSjKMbjkVM8cw3XoLtksT20OALtSS1YXlxf0qui6/q8ExUugJ/W3vG3RIDCVdwiZAsuVqg6MC70DlK",
	"CxlXfFHz9nE59fETsPKC3AePWv0TkXC7uLwXCX97ZN6ff78BikPUPgMCPW8STpPAu5uBn6/ivwXaH1SB",
	"bOFyqwaRHsMcLJLFDgGVyLVUDp7RXZFz48c85+9nsOXqc6qP66Icfc3d30w8iR55PQ4lK5xUiaOKWCq0",
	"dqvY9lNx6SzoawVSXXHjh+XJEpOP8Kzk4kGYqG5cEPDHf/4Lvfg1bOafz/eWOVse/7UYuBxkf2nt6z+B",
	"81NuPm6DGbgF32+HSa0frQbo7jRn5+NyzkvdrUlZn936QOC63+3eLrV1aw+U7tUh9TmUz8ty3rys8Drn",
	"RUrYTnXCU/q5/yp+5Y94kNVctXQuZ1E1ICi/0odlH9br9Yf1/wMAAP//8GWEmggaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
