// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package commanddb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID                 uuid.UUID        `json:"id"`
	SchemaName         string           `json:"schema_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	MigrationStatus    pgtype.Text      `json:"migration_status"`
	MigrationError     pgtype.Text      `json:"migration_error"`
	MigrationUpdatedAt pgtype.Timestamp `json:"migration_updated_at"`
}

type User struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}
