// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package commanddb

import (
	"context"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ListTenantSchemas(ctx context.Context) ([]string, error)
	UpdateTenantMigrationStatus(ctx context.Context, arg UpdateTenantMigrationStatusParams) error
}

var _ Querier = (*Queries)(nil)
