version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # podstawowe
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - gosimple

    # dodatkowe backendowe
    - gocritic
    - bodyclose
    - sqlclosecheck
    - nilerr
    - contextcheck
    - rowserrcheck

  settings:
    revive:
      severity: warning
      rules:
        - name: exported
        - name: unused-parameter
          disabled: true

    gocritic:
      enabled-checks:
        - appendAssign
        - argOrder
        - badLock
        - badRegexp
        - boolExprSimplify
        - builtinShadow
        - dupImport
        - emptyFallthrough
        - hugeParam
        - ifElseChain
        - mapKey
        - offBy1
        - regexpMust
        - sloppyReassign
        - sqlQuery
        - typeSwitchVar
        - unnecessaryBlock
        - weakCond

formatters:
  enable:
    - gofmt
    - goimports
    - gci

  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule

issues:
  max-issues-per-linter: 0
  max-same-issues: 0