// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: components.sql

package querydb

import (
	"context"

	"github.com/google/uuid"
)

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, name, description, code, manufacturer, manufacturer_url, price, weight_g, quantity, image_url, created_at FROM components WHERE id = $1
`

func (q *Queries) GetComponentByID(ctx context.Context, id uuid.UUID) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByID, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Manufacturer,
		&i.ManufacturerUrl,
		&i.Price,
		&i.WeightG,
		&i.Quantity,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listComponents = `-- name: ListComponents :many
SELECT id, name, description, code, manufacturer, manufacturer_url, price, weight_g, quantity, image_url, created_at FROM components ORDER BY name
`

func (q *Queries) ListComponents(ctx context.Context) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.Manufacturer,
			&i.ManufacturerUrl,
			&i.Price,
			&i.WeightG,
			&i.Quantity,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
