// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package querydb

import (
	"context"

	"github.com/google/uuid"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, tags, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const listProductComponentsByProductID = `-- name: ListProductComponentsByProductID :many
SELECT product_id, component_id, quantity
FROM product_components
WHERE product_id = $1
`

func (q *Queries) ListProductComponentsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductComponent, error) {
	rows, err := q.db.Query(ctx, listProductComponentsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductComponent{}
	for rows.Next() {
		var i ProductComponent
		if err := rows.Scan(&i.ProductID, &i.ComponentID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, tags, created_at FROM products ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
