// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package querydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetTodo(ctx context.Context, id uuid.UUID) (Todo, error)
	ListIncompleteTodos(ctx context.Context) ([]Todo, error)
	ListTodos(ctx context.Context) ([]Todo, error)
}

var _ Querier = (*Queries)(nil)
