// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package querydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetComponentByID(ctx context.Context, id uuid.UUID) (Component, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetTodo(ctx context.Context, id uuid.UUID) (Todo, error)
	ListComponents(ctx context.Context) ([]Component, error)
	ListIncompleteTodos(ctx context.Context) ([]Todo, error)
	ListProductComponentsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductComponent, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListTodos(ctx context.Context) ([]Todo, error)
}

var _ Querier = (*Queries)(nil)
