apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: go-hello-ns
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASS: strongpassword
  DB_NAME: appdb
  POSTGRES_PASSWORD: superadminpassword
