// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package querydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetTenantByID(ctx context.Context, id uuid.UUID) (GetTenantByIDRow, error)
	GetTenantBySchema(ctx context.Context, schemaName string) (GetTenantBySchemaRow, error)
	GetUserID(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
