// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package querydb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantByID = `-- name: GetTenantByID :one
SELECT
    id,
    schema_name,
    migration_status,
    migration_error,
    migration_updated_at,
    created_at
FROM tenants
WHERE id = $1
`

type GetTenantByIDRow struct {
	ID                 uuid.UUID        `json:"id"`
	SchemaName         string           `json:"schema_name"`
	MigrationStatus    pgtype.Text      `json:"migration_status"`
	MigrationError     pgtype.Text      `json:"migration_error"`
	MigrationUpdatedAt pgtype.Timestamp `json:"migration_updated_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.ID,
		&i.SchemaName,
		&i.MigrationStatus,
		&i.MigrationError,
		&i.MigrationUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantBySchema = `-- name: GetTenantBySchema :one
SELECT
    id,
    schema_name,
    migration_status,
    migration_error,
    migration_updated_at,
    created_at
FROM tenants
WHERE schema_name = $1
`

type GetTenantBySchemaRow struct {
	ID                 uuid.UUID        `json:"id"`
	SchemaName         string           `json:"schema_name"`
	MigrationStatus    pgtype.Text      `json:"migration_status"`
	MigrationError     pgtype.Text      `json:"migration_error"`
	MigrationUpdatedAt pgtype.Timestamp `json:"migration_updated_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetTenantBySchema(ctx context.Context, schemaName string) (GetTenantBySchemaRow, error) {
	row := q.db.QueryRow(ctx, getTenantBySchema, schemaName)
	var i GetTenantBySchemaRow
	err := row.Scan(
		&i.ID,
		&i.SchemaName,
		&i.MigrationStatus,
		&i.MigrationError,
		&i.MigrationUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
