// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package querydb

import (
	"context"

	"github.com/google/uuid"
)

const getUserID = `-- name: GetUserID :one
SELECT
    id,
    email
FROM users 
WHERE id = $1
`

func (q *Queries) GetUserID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}
