apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-sync
  namespace: go-migrations-ns
spec:
  tokenSecret:
    name: doppler-token
    namespace: go-migrations-ns
  managedSecret:
    name: my-migrations-secrets    # ← musi zgadzać się z secretName w values.yaml
    namespace: go-migrations-ns