replicaCount: 1

image:
  # repository: kkolcz/go-hello
  repository: go-hello-registry:5000/kkolcz/go-hello
  pullPolicy: IfNotPresent
  tag: "0.1.3"

service:
  type: ClusterIP
  port: 80

app:
  name: go-hello
  env:
    - name: APP_NAME
      value: "go-hello-from-helm"

    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: postgresql-secret
          key: DB_NAME

    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: postgresql-secret
          key: DB_USER

    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: postgresql-secret
          key: DB_PASS