{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "charts.fullname" . }}-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 240
  template:
    spec:
      restartPolicy: Never

      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for DB..."
              until nc -z $DB_HOST 5432; do
                sleep 2
              done
          envFrom:
            - secretRef:
                name: {{ .Values.app.secretName }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["/app", "migrate"]
          env:
{{ toYaml .Values.app.env | indent 12 }}
          {{- if .Values.app.secretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.app.secretName }}
          {{- end }}
{{- end }}