//go:build go1.22

// Package myhttpserver2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package myhttpserver2

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DetailedError defines model for DetailedError.
type DetailedError struct {
	// Code Technical code of the api_errors, used to identify the api_errors condition. This value is stable and can be used to handle specific api_errors cases.
	Code string `json:"code"`

	// Context Additional context of the api_errors
	Context *map[string]interface{} `json:"context,omitempty"`
	Details *[]Error                `json:"details,omitempty"`

	// Message Human readable message describing the reason and context of the api_errors, as well as possible instructions to resolve it. This value is subject to changes over time and must not be used to handle code logic decisions.
	Message  string    `json:"message"`
	MoreInfo *[]string `json:"moreInfo,omitempty"`

	// RequestID The unique identifier of the request
	RequestID *string `json:"requestID,omitempty"`

	// Status HTTP status code
	Status int `json:"status"`

	// Target The object that the api_errors relates to
	Target *string `json:"target,omitempty"`
}

// Error A structured api_errors response
type Error struct {
	// Code Technical code of the api_errors, used to identify the api_errors condition. This value is stable and can be used to handle specific api_errors cases.
	Code string `json:"code"`

	// Context Additional context of the api_errors
	Context *map[string]interface{} `json:"context,omitempty"`

	// Message Human readable message describing the reason and context of the api_errors, as well as possible instructions to resolve it. This value is subject to changes over time and must not be used to handle code logic decisions.
	Message string `json:"message"`
}

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	Error DetailedError `json:"error"`
}

// Test defines model for Test.
type Test struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
}

// N404 defines model for 404.
type N404 = ErrorMessage

// N500 defines model for 500.
type N500 = ErrorMessage

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Test endpoint
	// (GET /test)
	GetTest(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetTest operation middleware
func (siw *ServerInterfaceWrapper) GetTest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/test", wrapper.GetTest)

	return m
}

type N404JSONResponse ErrorMessage

type N500JSONResponse ErrorMessage

type GetTestRequestObject struct {
}

type GetTestResponseObject interface {
	VisitGetTestResponse(w http.ResponseWriter) error
}

type GetTest200JSONResponse Test

func (response GetTest200JSONResponse) VisitGetTestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTest404JSONResponse struct{ N404JSONResponse }

func (response GetTest404JSONResponse) VisitGetTestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTest500JSONResponse struct{ N500JSONResponse }

func (response GetTest500JSONResponse) VisitGetTestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Test endpoint
	// (GET /test)
	GetTest(ctx context.Context, request GetTestRequestObject) (GetTestResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetTest operation middleware
func (sh *strictHandler) GetTest(w http.ResponseWriter, r *http.Request) {
	var request GetTestRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTest(ctx, request.(GetTestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTestResponseObject); ok {
		if err := validResponse.VisitGetTestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWUY/bNgz+KwK3hw3w4rS9AoXfbrjrlrVNijRdH66Hg2IzsTpbciX61iDIfx8oyUkc",
	"p20wbPdwkW2KIj9++sgt5KZujEZNDrItWHSN0Q79w9X4in9yowk18VI2TaVyScro9JMzmt/hF1k3Ffa2",
	"8/pRVq1foLXGBkcFQgbT2eLh5ez99AYSUAVk8CT+/XLmX/cHCdTonFyzhzk609ochTYkVqbVBSTgSFLr",
	"ILsaX+12u10CLi+xlnzwjxZXkMEP6SHZNHx16S1H9ya69vsKdLlVDScJGSxKFFfjK/HT1JB4yWf9LGCX",
	"wPPx+P8AZzJd3M6n168f3t3O/7ydP9zO57P5vwZqogmtlpVwaB/RinDaAavn4/F/idWvshAWP7foCA5e",
	"ffI3SFJVWNx2+cqqmq0gu7vgRNglW2isadCSClgW3p1fKsLaXRQ5l402DQMjrZUbfq6NxYlemZ6nflav",
	"lf7LCSolCa62VFrwLqH0ytja11vIpWlJUIlCNurBw+wg6coPGZREjcvStMSqGcXXo9zUsA/JkVV6fS7G",
	"COnkZhgbs7PV6nOLQhWoSa0UWmFWPpSuFMdxXEihQUwdY04D+H2xeCvCR+EpvN+rNOEaA+jSrpHOR2+W",
	"nzCnAG8fP2GxkoROkOml8HEPpmzUiDAvtcqlVW3NgKaPaB1fQbNUmFN6ScIfYZhyxF1ZLCC76/K/39uF",
	"uGE3fJPAnuT9dK+FI9vm1Fos+nlGYUhOWB40YYBazLjygHfFPvhLROuwEGQ6SmxOgc2NLhR7G4lFqZzw",
	"aiSU40IuKxRSFyKXWixx76qUuqhQuAZztVJ5z5t06Ea9Er2fvprOPkz36jWgk5fNL2cocV2EyHx23maY",
	"IJyBfK95A4K2tdTCoix8atFOBKOl0ut4VaTja8yJf+3YREgn/saq4t/GOKfYodKhqMpoZioX01SPKBQN",
	"wG0j1Y3IS6nX6IRhUSZVB8jr1pFvaUPcfaUrs1a5KDBXTPATyBeHC8+1i24aa3J0DovvEjxe3g7Hr9L6",
	"zQHoPln3nexbOtxvA6cxBBfnjl6wjmXDLnBU6e2QZdw0txBUGjJoW/V9HLzJseNhOCyHmLdW0eYd5xWC",
	"WaK0aK9bKg9PL7uj//iwgNgP2VP4eoiFBS00VBV7ESkKZeV6Xr+dQAJR2FjER+PRmBM0DWrZKMhYwBpJ",
	"pY8kpYhWFF2GzLepCQ8RvyEtQlfog1lvQjDbswAdjYVPL5p8LpsoFmFUGEwSs1ecXhxAzznYR5Sy0WEe",
	"+7YtGx2XD7K7+wRcW9fSbjq0UReNUTrGtUf42Wg8esZF9KOU86PLiXa9ncRBCxJobQUZbEPJd1mabkvj",
	"aJfWG9+9vNnT9PFJuiXUUtOOKyytYpXyMLN5IPlKthWTqDK5rPh19mL8wte/I9SxledSAqjbmvkcH/2h",
	"cM/N2B/X39Otzg2/wV5MbsTKWC+JnGeUmqhxygkpulskGmlljYR2xBDe7/4JAAD//19xotZlDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
