// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package commanddb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteTodo(ctx context.Context, id uuid.UUID) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, id uuid.UUID) error
	UpdateTenantMigrationStatus(ctx context.Context, arg UpdateTenantMigrationStatusParams) error
}

var _ Querier = (*Queries)(nil)
