// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tenants.sql

package commanddb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    id,
    schema_name
)
VALUES (
    $1,
    $2
)
RETURNING id, schema_name, created_at, migration_status, migration_error, migration_updated_at
`

type CreateTenantParams struct {
	ID         uuid.UUID `json:"id"`
	SchemaName string    `json:"schema_name"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.SchemaName)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.SchemaName,
		&i.CreatedAt,
		&i.MigrationStatus,
		&i.MigrationError,
		&i.MigrationUpdatedAt,
	)
	return i, err
}

const listTenantSchemas = `-- name: ListTenantSchemas :many
SELECT schema_name FROM tenants
`

func (q *Queries) ListTenantSchemas(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTenantSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var schema_name string
		if err := rows.Scan(&schema_name); err != nil {
			return nil, err
		}
		items = append(items, schema_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantMigrationStatus = `-- name: UpdateTenantMigrationStatus :exec
UPDATE tenants
SET
    migration_status = $2,
    migration_error = $3,
    migration_updated_at = NOW()
WHERE id = $1
`

type UpdateTenantMigrationStatusParams struct {
	ID              uuid.UUID   `json:"id"`
	MigrationStatus pgtype.Text `json:"migration_status"`
	MigrationError  pgtype.Text `json:"migration_error"`
}

func (q *Queries) UpdateTenantMigrationStatus(ctx context.Context, arg UpdateTenantMigrationStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantMigrationStatus, arg.ID, arg.MigrationStatus, arg.MigrationError)
	return err
}
