// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todos.sql

package commanddb

import (
	"context"

	"github.com/google/uuid"
)

const completeTodo = `-- name: CompleteTodo :exec
UPDATE todos
SET completed = true
WHERE id = $1
`

func (q *Queries) CompleteTodo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeTodo, id)
	return err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    id,
    title
)
VALUES (
    $1,
    $2
)
RETURNING id, title, completed, created_at
`

type CreateTodoParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.ID, arg.Title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}
