//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Component defines model for Component.
type Component struct {
	Code            string             `json:"code"`
	CreatedAt       *time.Time         `json:"created_at,omitempty"`
	Description     *string            `json:"description,omitempty"`
	Id              openapi_types.UUID `json:"id"`
	ImageUrl        *string            `json:"image_url,omitempty"`
	Manufacturer    *string            `json:"manufacturer,omitempty"`
	ManufacturerUrl *string            `json:"manufacturer_url,omitempty"`
	Name            string             `json:"name"`
	Price           *float64           `json:"price,omitempty"`
	Quantity        *int               `json:"quantity,omitempty"`
	WeightG         *int               `json:"weight_g,omitempty"`
}

// CreateComponentRequest defines model for CreateComponentRequest.
type CreateComponentRequest struct {
	Code            string   `json:"code"`
	Description     *string  `json:"description,omitempty"`
	ImageUrl        *string  `json:"image_url,omitempty"`
	Manufacturer    *string  `json:"manufacturer,omitempty"`
	ManufacturerUrl *string  `json:"manufacturer_url,omitempty"`
	Name            string   `json:"name"`
	Price           *float64 `json:"price,omitempty"`
	Quantity        *int     `json:"quantity,omitempty"`
	WeightG         *int     `json:"weight_g,omitempty"`
}

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	Description *string   `json:"description,omitempty"`
	Name        string    `json:"name"`
	Price       *float64  `json:"price,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
}

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	SchemaName string `json:"schema_name"`
}

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Title string `json:"title"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email openapi_types.Email `json:"email"`
}

// CreatedResponse defines model for CreatedResponse.
type CreatedResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// DetailedError defines model for DetailedError.
type DetailedError struct {
	Code      string                  `json:"code"`
	Context   *map[string]interface{} `json:"context,omitempty"`
	Details   *[]Error                `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId *openapi_types.UUID     `json:"request_id,omitempty"`
	Status    int                     `json:"status"`
	Target    *string                 `json:"target,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Context *map[string]interface{} `json:"context,omitempty"`
	Message string                  `json:"message"`
}

// ErrorMessage defines model for ErrorMessage.
type ErrorMessage struct {
	Error DetailedError `json:"error"`
}

// Product defines model for Product.
type Product struct {
	CreatedAt   *time.Time         `json:"created_at,omitempty"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Price       *float64           `json:"price,omitempty"`
	Recipe      *[]RecipeItem      `json:"recipe,omitempty"`
	Tags        *[]string          `json:"tags,omitempty"`
}

// RecipeItem defines model for RecipeItem.
type RecipeItem struct {
	ComponentId openapi_types.UUID `json:"component_id"`
	Quantity    int                `json:"quantity"`
}

// SetProductComponentRequest defines model for SetProductComponentRequest.
type SetProductComponentRequest struct {
	Quantity int `json:"quantity"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	CreatedAt        *time.Time         `json:"created_at,omitempty"`
	Id               openapi_types.UUID `json:"id"`
	MigrationError   *string            `json:"migration_error,omitempty"`
	MigrationStatus  *string            `json:"migration_status,omitempty"`
	MigrationUpdated *time.Time         `json:"migration_updated,omitempty"`
	SchemaName       string             `json:"schema_name"`
}

// Todo defines model for Todo.
type Todo struct {
	Completed bool               `json:"completed"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
}

// TodoList defines model for TodoList.
type TodoList = []Todo

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
}

// ComponentID defines model for ComponentID.
type ComponentID = openapi_types.UUID

// ID defines model for ID.
type ID = openapi_types.UUID

// XTenantID defines model for XTenantID.
type XTenantID = openapi_types.UUID

// N400 defines model for 400.
type N400 = ErrorMessage

// N404 defines model for 404.
type N404 = ErrorMessage

// N409 defines model for 409.
type N409 = ErrorMessage

// N500 defines model for 500.
type N500 = ErrorMessage

// CreateComponentParams defines parameters for CreateComponent.
type CreateComponentParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// GetComponentParams defines parameters for GetComponent.
type GetComponentParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// CreateProductParams defines parameters for CreateProduct.
type CreateProductParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// GetProductParams defines parameters for GetProduct.
type GetProductParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// RemoveProductComponentParams defines parameters for RemoveProductComponent.
type RemoveProductComponentParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// SetProductComponentParams defines parameters for SetProductComponent.
type SetProductComponentParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// ListTodosParams defines parameters for ListTodos.
type ListTodosParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// CreateTodoParams defines parameters for CreateTodo.
type CreateTodoParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// DeleteTodoParams defines parameters for DeleteTodo.
type DeleteTodoParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// GetTodoParams defines parameters for GetTodo.
type GetTodoParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// CompleteTodoParams defines parameters for CompleteTodo.
type CompleteTodoParams struct {
	// XTenantID Tenant identifier — maps to the PostgreSQL schema for this tenant
	XTenantID XTenantID `json:"X-Tenant-ID"`
}

// CreateComponentJSONRequestBody defines body for CreateComponent for application/json ContentType.
type CreateComponentJSONRequestBody = CreateComponentRequest

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = CreateProductRequest

// SetProductComponentJSONRequestBody defines body for SetProductComponent for application/json ContentType.
type SetProductComponentJSONRequestBody = SetProductComponentRequest

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new component (half-product)
	// (POST /components)
	CreateComponent(w http.ResponseWriter, r *http.Request, params CreateComponentParams)
	// Get a component by ID
	// (GET /components/{id})
	GetComponent(w http.ResponseWriter, r *http.Request, id ID, params GetComponentParams)
	// Create a new product
	// (POST /products)
	CreateProduct(w http.ResponseWriter, r *http.Request, params CreateProductParams)
	// Get a product by ID
	// (GET /products/{id})
	GetProduct(w http.ResponseWriter, r *http.Request, id ID, params GetProductParams)
	// Usuń komponent z receptury produktu
	// (DELETE /products/{id}/components/{componentId})
	RemoveProductComponent(w http.ResponseWriter, r *http.Request, id ID, componentId ComponentID, params RemoveProductComponentParams)
	// Dodaj lub zaktualizuj komponent w recepturze produktu
	// (PUT /products/{id}/components/{componentId})
	SetProductComponent(w http.ResponseWriter, r *http.Request, id ID, componentId ComponentID, params SetProductComponentParams)
	// Create a new tenant
	// (POST /tenants)
	CreateTenant(w http.ResponseWriter, r *http.Request)
	// Get a tenant by ID
	// (GET /tenants/{id})
	GetTenant(w http.ResponseWriter, r *http.Request, id ID)
	// list todos
	// (GET /todos)
	ListTodos(w http.ResponseWriter, r *http.Request, params ListTodosParams)
	// Create a new todo
	// (POST /todos)
	CreateTodo(w http.ResponseWriter, r *http.Request, params CreateTodoParams)
	// Delete a todo
	// (DELETE /todos/{id})
	DeleteTodo(w http.ResponseWriter, r *http.Request, id ID, params DeleteTodoParams)
	// Get a todo by ID
	// (GET /todos/{id})
	GetTodo(w http.ResponseWriter, r *http.Request, id ID, params GetTodoParams)
	// Mark a todo as completed
	// (PUT /todos/{id}/complete)
	CompleteTodo(w http.ResponseWriter, r *http.Request, id ID, params CompleteTodoParams)
	// Create a new user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Get a user by ID
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id ID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateComponent operation middleware
func (siw *ServerInterfaceWrapper) CreateComponent(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateComponentParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateComponent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetComponent operation middleware
func (siw *ServerInterfaceWrapper) GetComponent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetComponentParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetComponent(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProductParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProduct(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveProductComponent operation middleware
func (siw *ServerInterfaceWrapper) RemoveProductComponent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "componentId" -------------
	var componentId ComponentID

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", r.PathValue("componentId"), &componentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "componentId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RemoveProductComponentParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveProductComponent(w, r, id, componentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetProductComponent operation middleware
func (siw *ServerInterfaceWrapper) SetProductComponent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "componentId" -------------
	var componentId ComponentID

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", r.PathValue("componentId"), &componentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "componentId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SetProductComponentParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetProductComponent(w, r, id, componentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTenant operation middleware
func (siw *ServerInterfaceWrapper) CreateTenant(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTenant(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTenant operation middleware
func (siw *ServerInterfaceWrapper) GetTenant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTenant(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTodosParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTodos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTodoParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTodo(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTodoParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTodo(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTodoParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTodo(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteTodo operation middleware
func (siw *ServerInterfaceWrapper) CompleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteTodoParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID XTenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteTodo(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/components", wrapper.CreateComponent)
	m.HandleFunc("GET "+options.BaseURL+"/components/{id}", wrapper.GetComponent)
	m.HandleFunc("POST "+options.BaseURL+"/products", wrapper.CreateProduct)
	m.HandleFunc("GET "+options.BaseURL+"/products/{id}", wrapper.GetProduct)
	m.HandleFunc("DELETE "+options.BaseURL+"/products/{id}/components/{componentId}", wrapper.RemoveProductComponent)
	m.HandleFunc("PUT "+options.BaseURL+"/products/{id}/components/{componentId}", wrapper.SetProductComponent)
	m.HandleFunc("POST "+options.BaseURL+"/tenants", wrapper.CreateTenant)
	m.HandleFunc("GET "+options.BaseURL+"/tenants/{id}", wrapper.GetTenant)
	m.HandleFunc("GET "+options.BaseURL+"/todos", wrapper.ListTodos)
	m.HandleFunc("POST "+options.BaseURL+"/todos", wrapper.CreateTodo)
	m.HandleFunc("DELETE "+options.BaseURL+"/todos/{id}", wrapper.DeleteTodo)
	m.HandleFunc("GET "+options.BaseURL+"/todos/{id}", wrapper.GetTodo)
	m.HandleFunc("PUT "+options.BaseURL+"/todos/{id}/complete", wrapper.CompleteTodo)
	m.HandleFunc("POST "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{id}", wrapper.GetUser)

	return m
}

type N400JSONResponse ErrorMessage

type N404JSONResponse ErrorMessage

type N409JSONResponse ErrorMessage

type N500JSONResponse ErrorMessage

type CreateComponentRequestObject struct {
	Params CreateComponentParams
	Body   *CreateComponentJSONRequestBody
}

type CreateComponentResponseObject interface {
	VisitCreateComponentResponse(w http.ResponseWriter) error
}

type CreateComponent201JSONResponse CreatedResponse

func (response CreateComponent201JSONResponse) VisitCreateComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateComponent400JSONResponse struct{ N400JSONResponse }

func (response CreateComponent400JSONResponse) VisitCreateComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateComponent500JSONResponse struct{ N500JSONResponse }

func (response CreateComponent500JSONResponse) VisitCreateComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetComponentRequestObject struct {
	Id     ID `json:"id"`
	Params GetComponentParams
}

type GetComponentResponseObject interface {
	VisitGetComponentResponse(w http.ResponseWriter) error
}

type GetComponent200JSONResponse Component

func (response GetComponent200JSONResponse) VisitGetComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetComponent404JSONResponse struct{ N404JSONResponse }

func (response GetComponent404JSONResponse) VisitGetComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetComponent500JSONResponse struct{ N500JSONResponse }

func (response GetComponent500JSONResponse) VisitGetComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateProductRequestObject struct {
	Params CreateProductParams
	Body   *CreateProductJSONRequestBody
}

type CreateProductResponseObject interface {
	VisitCreateProductResponse(w http.ResponseWriter) error
}

type CreateProduct201JSONResponse CreatedResponse

func (response CreateProduct201JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct400JSONResponse struct{ N400JSONResponse }

func (response CreateProduct400JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct500JSONResponse struct{ N500JSONResponse }

func (response CreateProduct500JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProductRequestObject struct {
	Id     ID `json:"id"`
	Params GetProductParams
}

type GetProductResponseObject interface {
	VisitGetProductResponse(w http.ResponseWriter) error
}

type GetProduct200JSONResponse Product

func (response GetProduct200JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProduct404JSONResponse struct{ N404JSONResponse }

func (response GetProduct404JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProduct500JSONResponse struct{ N500JSONResponse }

func (response GetProduct500JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RemoveProductComponentRequestObject struct {
	Id          ID          `json:"id"`
	ComponentId ComponentID `json:"componentId"`
	Params      RemoveProductComponentParams
}

type RemoveProductComponentResponseObject interface {
	VisitRemoveProductComponentResponse(w http.ResponseWriter) error
}

type RemoveProductComponent204Response struct {
}

func (response RemoveProductComponent204Response) VisitRemoveProductComponentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveProductComponent404JSONResponse struct{ N404JSONResponse }

func (response RemoveProductComponent404JSONResponse) VisitRemoveProductComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RemoveProductComponent500JSONResponse struct{ N500JSONResponse }

func (response RemoveProductComponent500JSONResponse) VisitRemoveProductComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SetProductComponentRequestObject struct {
	Id          ID          `json:"id"`
	ComponentId ComponentID `json:"componentId"`
	Params      SetProductComponentParams
	Body        *SetProductComponentJSONRequestBody
}

type SetProductComponentResponseObject interface {
	VisitSetProductComponentResponse(w http.ResponseWriter) error
}

type SetProductComponent204Response struct {
}

func (response SetProductComponent204Response) VisitSetProductComponentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetProductComponent400JSONResponse struct{ N400JSONResponse }

func (response SetProductComponent400JSONResponse) VisitSetProductComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SetProductComponent404JSONResponse struct{ N404JSONResponse }

func (response SetProductComponent404JSONResponse) VisitSetProductComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SetProductComponent500JSONResponse struct{ N500JSONResponse }

func (response SetProductComponent500JSONResponse) VisitSetProductComponentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTenantRequestObject struct {
	Body *CreateTenantJSONRequestBody
}

type CreateTenantResponseObject interface {
	VisitCreateTenantResponse(w http.ResponseWriter) error
}

type CreateTenant201JSONResponse CreatedResponse

func (response CreateTenant201JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTenant400JSONResponse struct{ N400JSONResponse }

func (response CreateTenant400JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTenant409JSONResponse struct{ N409JSONResponse }

func (response CreateTenant409JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateTenant500JSONResponse struct{ N500JSONResponse }

func (response CreateTenant500JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTenantRequestObject struct {
	Id ID `json:"id"`
}

type GetTenantResponseObject interface {
	VisitGetTenantResponse(w http.ResponseWriter) error
}

type GetTenant200JSONResponse Tenant

func (response GetTenant200JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTenant404JSONResponse struct{ N404JSONResponse }

func (response GetTenant404JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTenant500JSONResponse struct{ N500JSONResponse }

func (response GetTenant500JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTodosRequestObject struct {
	Params ListTodosParams
}

type ListTodosResponseObject interface {
	VisitListTodosResponse(w http.ResponseWriter) error
}

type ListTodos200JSONResponse TodoList

func (response ListTodos200JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTodos400JSONResponse struct{ N400JSONResponse }

func (response ListTodos400JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListTodos500JSONResponse struct{ N500JSONResponse }

func (response ListTodos500JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTodoRequestObject struct {
	Params CreateTodoParams
	Body   *CreateTodoJSONRequestBody
}

type CreateTodoResponseObject interface {
	VisitCreateTodoResponse(w http.ResponseWriter) error
}

type CreateTodo201JSONResponse CreatedResponse

func (response CreateTodo201JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTodo400JSONResponse struct{ N400JSONResponse }

func (response CreateTodo400JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTodo500JSONResponse struct{ N500JSONResponse }

func (response CreateTodo500JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTodoRequestObject struct {
	Id     ID `json:"id"`
	Params DeleteTodoParams
}

type DeleteTodoResponseObject interface {
	VisitDeleteTodoResponse(w http.ResponseWriter) error
}

type DeleteTodo204Response struct {
}

func (response DeleteTodo204Response) VisitDeleteTodoResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTodo404JSONResponse struct{ N404JSONResponse }

func (response DeleteTodo404JSONResponse) VisitDeleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTodo500JSONResponse struct{ N500JSONResponse }

func (response DeleteTodo500JSONResponse) VisitDeleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTodoRequestObject struct {
	Id     ID `json:"id"`
	Params GetTodoParams
}

type GetTodoResponseObject interface {
	VisitGetTodoResponse(w http.ResponseWriter) error
}

type GetTodo200JSONResponse Todo

func (response GetTodo200JSONResponse) VisitGetTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTodo404JSONResponse struct{ N404JSONResponse }

func (response GetTodo404JSONResponse) VisitGetTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTodo500JSONResponse struct{ N500JSONResponse }

func (response GetTodo500JSONResponse) VisitGetTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTodoRequestObject struct {
	Id     ID `json:"id"`
	Params CompleteTodoParams
}

type CompleteTodoResponseObject interface {
	VisitCompleteTodoResponse(w http.ResponseWriter) error
}

type CompleteTodo204Response struct {
}

func (response CompleteTodo204Response) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CompleteTodo404JSONResponse struct{ N404JSONResponse }

func (response CompleteTodo404JSONResponse) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTodo409JSONResponse struct{ N409JSONResponse }

func (response CompleteTodo409JSONResponse) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CompleteTodo500JSONResponse struct{ N500JSONResponse }

func (response CompleteTodo500JSONResponse) VisitCompleteTodoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse CreatedResponse

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse struct{ N400JSONResponse }

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser409JSONResponse struct{ N409JSONResponse }

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse struct{ N500JSONResponse }

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUserRequestObject struct {
	Id ID `json:"id"`
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse User

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUser404JSONResponse struct{ N404JSONResponse }

func (response GetUser404JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetUser500JSONResponse struct{ N500JSONResponse }

func (response GetUser500JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new component (half-product)
	// (POST /components)
	CreateComponent(ctx context.Context, request CreateComponentRequestObject) (CreateComponentResponseObject, error)
	// Get a component by ID
	// (GET /components/{id})
	GetComponent(ctx context.Context, request GetComponentRequestObject) (GetComponentResponseObject, error)
	// Create a new product
	// (POST /products)
	CreateProduct(ctx context.Context, request CreateProductRequestObject) (CreateProductResponseObject, error)
	// Get a product by ID
	// (GET /products/{id})
	GetProduct(ctx context.Context, request GetProductRequestObject) (GetProductResponseObject, error)
	// Usuń komponent z receptury produktu
	// (DELETE /products/{id}/components/{componentId})
	RemoveProductComponent(ctx context.Context, request RemoveProductComponentRequestObject) (RemoveProductComponentResponseObject, error)
	// Dodaj lub zaktualizuj komponent w recepturze produktu
	// (PUT /products/{id}/components/{componentId})
	SetProductComponent(ctx context.Context, request SetProductComponentRequestObject) (SetProductComponentResponseObject, error)
	// Create a new tenant
	// (POST /tenants)
	CreateTenant(ctx context.Context, request CreateTenantRequestObject) (CreateTenantResponseObject, error)
	// Get a tenant by ID
	// (GET /tenants/{id})
	GetTenant(ctx context.Context, request GetTenantRequestObject) (GetTenantResponseObject, error)
	// list todos
	// (GET /todos)
	ListTodos(ctx context.Context, request ListTodosRequestObject) (ListTodosResponseObject, error)
	// Create a new todo
	// (POST /todos)
	CreateTodo(ctx context.Context, request CreateTodoRequestObject) (CreateTodoResponseObject, error)
	// Delete a todo
	// (DELETE /todos/{id})
	DeleteTodo(ctx context.Context, request DeleteTodoRequestObject) (DeleteTodoResponseObject, error)
	// Get a todo by ID
	// (GET /todos/{id})
	GetTodo(ctx context.Context, request GetTodoRequestObject) (GetTodoResponseObject, error)
	// Mark a todo as completed
	// (PUT /todos/{id}/complete)
	CompleteTodo(ctx context.Context, request CompleteTodoRequestObject) (CompleteTodoResponseObject, error)
	// Create a new user
	// (POST /users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Get a user by ID
	// (GET /users/{id})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateComponent operation middleware
func (sh *strictHandler) CreateComponent(w http.ResponseWriter, r *http.Request, params CreateComponentParams) {
	var request CreateComponentRequestObject

	request.Params = params

	var body CreateComponentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateComponent(ctx, request.(CreateComponentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateComponent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateComponentResponseObject); ok {
		if err := validResponse.VisitCreateComponentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetComponent operation middleware
func (sh *strictHandler) GetComponent(w http.ResponseWriter, r *http.Request, id ID, params GetComponentParams) {
	var request GetComponentRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetComponent(ctx, request.(GetComponentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetComponent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetComponentResponseObject); ok {
		if err := validResponse.VisitGetComponentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProduct operation middleware
func (sh *strictHandler) CreateProduct(w http.ResponseWriter, r *http.Request, params CreateProductParams) {
	var request CreateProductRequestObject

	request.Params = params

	var body CreateProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduct(ctx, request.(CreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProductResponseObject); ok {
		if err := validResponse.VisitCreateProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProduct operation middleware
func (sh *strictHandler) GetProduct(w http.ResponseWriter, r *http.Request, id ID, params GetProductParams) {
	var request GetProductRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProduct(ctx, request.(GetProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProductResponseObject); ok {
		if err := validResponse.VisitGetProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveProductComponent operation middleware
func (sh *strictHandler) RemoveProductComponent(w http.ResponseWriter, r *http.Request, id ID, componentId ComponentID, params RemoveProductComponentParams) {
	var request RemoveProductComponentRequestObject

	request.Id = id
	request.ComponentId = componentId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveProductComponent(ctx, request.(RemoveProductComponentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveProductComponent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveProductComponentResponseObject); ok {
		if err := validResponse.VisitRemoveProductComponentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetProductComponent operation middleware
func (sh *strictHandler) SetProductComponent(w http.ResponseWriter, r *http.Request, id ID, componentId ComponentID, params SetProductComponentParams) {
	var request SetProductComponentRequestObject

	request.Id = id
	request.ComponentId = componentId
	request.Params = params

	var body SetProductComponentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetProductComponent(ctx, request.(SetProductComponentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetProductComponent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetProductComponentResponseObject); ok {
		if err := validResponse.VisitSetProductComponentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTenant operation middleware
func (sh *strictHandler) CreateTenant(w http.ResponseWriter, r *http.Request) {
	var request CreateTenantRequestObject

	var body CreateTenantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTenant(ctx, request.(CreateTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTenantResponseObject); ok {
		if err := validResponse.VisitCreateTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTenant operation middleware
func (sh *strictHandler) GetTenant(w http.ResponseWriter, r *http.Request, id ID) {
	var request GetTenantRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTenant(ctx, request.(GetTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTenant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTenantResponseObject); ok {
		if err := validResponse.VisitGetTenantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTodos operation middleware
func (sh *strictHandler) ListTodos(w http.ResponseWriter, r *http.Request, params ListTodosParams) {
	var request ListTodosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTodos(ctx, request.(ListTodosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTodos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTodosResponseObject); ok {
		if err := validResponse.VisitListTodosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTodo operation middleware
func (sh *strictHandler) CreateTodo(w http.ResponseWriter, r *http.Request, params CreateTodoParams) {
	var request CreateTodoRequestObject

	request.Params = params

	var body CreateTodoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTodo(ctx, request.(CreateTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTodoResponseObject); ok {
		if err := validResponse.VisitCreateTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTodo operation middleware
func (sh *strictHandler) DeleteTodo(w http.ResponseWriter, r *http.Request, id ID, params DeleteTodoParams) {
	var request DeleteTodoRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTodo(ctx, request.(DeleteTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTodoResponseObject); ok {
		if err := validResponse.VisitDeleteTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTodo operation middleware
func (sh *strictHandler) GetTodo(w http.ResponseWriter, r *http.Request, id ID, params GetTodoParams) {
	var request GetTodoRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTodo(ctx, request.(GetTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTodoResponseObject); ok {
		if err := validResponse.VisitGetTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteTodo operation middleware
func (sh *strictHandler) CompleteTodo(w http.ResponseWriter, r *http.Request, id ID, params CompleteTodoParams) {
	var request CompleteTodoRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteTodo(ctx, request.(CompleteTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteTodoResponseObject); ok {
		if err := validResponse.VisitCompleteTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(w http.ResponseWriter, r *http.Request, id ID) {
	var request GetUserRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx, request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		if err := validResponse.VisitGetUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra3W7juBV+FYLtRQsosdLNAju+6kziXRibn1kn0y4wGBiMdGxzIoka/iTjBAZ60Ufo",
	"TR+h79He9iH6JAVJ/dqUpYl/4r1KbJM83znf+eORnnHA4pQlkEiB+884JZzEIIGbT2f5b8Nz/ZEmuI9T",
	"ImfYwwmJAffL3cMQe5jDF0U5hLgvuQIPi2AGMdFbJ4zHROI+VorqlXKe6u1CcppM8WLh4UYRdNOTf72F",
	"hOQ6hCACTlNJmZZkf0E0hETSCQWO/ve3f6CYpAJJhuQM0Hsm5JTDzS8XyMpEE8aRnFGBpNmMPQt6BiQE",
	"XsL+9cgefjQ83wj/Qm8WKUsEGE5OfV//CVgiIZH6X5KmEQ2IVqn3WWi9njF8JXEa2R35dv3/A4mU+Qc4",
	"Z9weFGp5796ej0eDXz4Mbm6xh2MQgkz19yP4okBIdMfCOUqYRJrxiGqrPVI5QyKFgE4y8djDQhKpBO6f",
	"+v7CgC81/T2HCe7j3/VKl+vZX0VvoOFcZlLNvjpR70iIuIWCFx4+9U93YYSr69vxj9cfrs6XTCCY4gEY",
	"9SdMJWFNz9Nt6nlViDBavtmFlmfXVz9eDM9u3UqSiAMJ5wi+UiFFTdM329T0jCWTiAaGzu9349PDq9vB",
	"6OrtxfhmMPrLYDQejEbXo5rWw0QCT0iEBPAH4MieUOr8/Xa92C2uPL+edE0+5iwFLqnV2ur1vJwjPBxw",
	"IBLCMZG1lBISCUeSxrCaV5agOc6kYYf05GEakymMFY+ch8QkURMSSMWBty5oPMWmVMcPKacB1FVm6i6q",
	"6Juo+A64XvtFkURSOa8cRBMJU/vrI9DpTI6nrl8X1fz90RYkA8mzjHwqpLG7z2Bd+swwUnCZpdFmSjPn",
	"1pE4uDk68X9+EWV75KICGAQVknF04t//918u3C+lKYQJUZHEfd/bjLJubL3nLFRBM1dt5l81zV9pOAWJ",
	"3nO2qVkkmRoMVEIsnNKzLwjnZO42QLPmtlVpVNxmp/GqfiRw5ZYl2dXdayCwkDUCkFRGS6LfqTmKaXTf",
	"Kt7ubRb8QQBvFAwxoVFdsBLA/5x9PA5YjL2SP7u8DZFd1YwoHFWqWx1Pp6S8mq9css5BEhpBOMirJomi",
	"6wnuf+xQ4/DCWw0OfVzdR7ucs+S3FjoIOe5Yf/JS7UrqkvApSEe0LHuoPWPVSi67FfZqS+TVbnK1Yute",
	"52sVWymh6E+WsuxqF7peLQOpPK5RmctS3pL356quI7LuRyu+br51ic6yrcOSr9fMbKXR4BDQFDoHwsgs",
	"H0qIXdGwYd4vexUXBRXRDn/OkHYNxHX91YpjVs6u7HRhvAGZeUp7M1WFUETOie/hmCY0VjHun3ht2NaC",
	"sXVyOy7b0awxnXJzDxoX0VgmhfUbytRY7hAqCECI9RtVqpGH3XXZrEEwird1Cbo/cHtpBBnWbM8dYxGQ",
	"5KX3oo68bNKS2BPNAV5FhSa1L6h19k7pxNjJkUh0m7Or/sZ7aV/iNfZCejFNJqzS/eHLObrMfVSgt++H",
	"2MMPwIW9XJ8c+8e+xsJSSEhKcR9/d+wff4c9M1A06vaWpp3MGlZbxJw6DHF/+epm9pdT0Yb2qFzSK+eN",
	"un/I2pl3LJx3mHF0mzM0XC4XdQtLrmB5evgn/2TLKMpm1TnkyXahLBLtWMtvOrrA2tOLysnQ+rV6kRmi",
	"qDgmfF5QiAhK4BEVe9AfZiSaHKW2nPwR59X1Iw6IJBGb4k/6mKqQZxouNICsjaw7yk8gt+IlXuviwpdq",
	"VPrbo7JQYy2JlcnkaRcKTzeg8CeQiFS4u5sjM0l3U5Zx2hrVedN5qDG9NII4vIjOAL5mPKcFh+t9oTV4",
	"t+AMrx+6uRJruNp/2GYUdAxaQ1Qt61YeKy7scEF3SKskjiBmD7B8P9g9oe2rqo9OHfyfrj6L/LlIdUqo",
	"hP77n3KOnhCHAFKp+HxP/H0Q6j9/R/cFlgoCy+q9VE5CPZwqR5g5rm+HSc/2M/qam2unvN7iI5I8UpbM",
	"0WPB0BN8azreg0Ods5B8RpG6Q0/kXioS0Sf1ueJgVfjrPUynDPvMvbXM3+aP5ndXqesj88Mr1NmrDS+s",
	"09mj57a1b7ZV04t3KXLac6JrtLdW9IL3b0swu67RGaxmlvZfoa1FVwr0ktlZyESjvS+okLdmxabd9K7M",
	"ns9OHIaPqJDI6refFrYisGJu89kUz3XZjIXsYG8s1ed2B5gFWche864iLXXLfBfBVWS0pg733Hy/qQe8",
	"9JriaEGMRS3afWUsawOdtNzW9JrrwSvZbbs5rNGxX6FsaLErRcPp1b18sG2aNdfd4CxbcGjeHRN+DyEi",
	"ApWz+W808h76p0vC73NGalDdxCiRvdS7rtKYhwS7rBbVly0Or1podL+VjllZqnKqLb0Vqlt75Yzrw+qU",
	"DagmZvaf7rQlV9JdYWq9wbzIaU1XR3zBAhKhEB4gYmlsxx7mnTo8kzLt93qRXjBjQvZ/8H/wew8nePFp",
	"8f8AAAD//6dNnCuQLwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
