// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTodo = `-- name: CompleteTodo :exec
UPDATE todos
SET
    status     = 'done',
    updated_at = $2
WHERE id = $1
`

type CompleteTodoParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Sets status = 'done' for a single todo.
// This query only touches status + updated_at, making it impossible to
// accidentally change the title during a Complete operation.
func (q *Queries) CompleteTodo(ctx context.Context, arg CompleteTodoParams) error {
	_, err := q.db.Exec(ctx, completeTodo, arg.ID, arg.UpdatedAt)
	return err
}

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (id, title, description, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTodoParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	Status      TodoStatus         `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Inserts a new todo row. The ID is supplied by the application (pre-generated
// in the HTTP handler), not by the database default, so we know it before
// executing the query.
func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.Exec(ctx, createTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, title, description, status, created_at, updated_at
FROM todos
WHERE id = $1
`

func (q *Queries) GetTodoByID(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, status, created_at, updated_at
FROM todos
ORDER BY created_at DESC
`

// Returns all todos ordered by creation time (newest first).
func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET
    title       = $2,
    description = $3,
    updated_at  = $4
WHERE id = $1
`

type UpdateTodoParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Updates only title, description, and updated_at.
// Status is intentionally excluded — it is managed by CompleteTodo below.
// Having two separate queries mirrors the CQRS command split on the
// application side: UpdateTodoCommand ≠ CompleteTodoCommand.
func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.Exec(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.UpdatedAt,
	)
	return err
}
